title: xNifty
description: Documentation for <a href="https://snoring.ninja" target="_blank">Snoring Ninja</a> projects by xNifty
show_downloads: false
git_branch: master
logo_url: /assets/images/logo.png
google_analytics:
theme: 
wiki_folder: wiki
use_github_wiki: false
use_prose_io: true
google_cse_token: 
custom_head: false
custom_sidebar: false
custom_footer: false
repository: xnifty/xnifty.github.io
github: [metadata]
kramdown:  
  parse_block_html: true
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
